# Generated by Django 5.1.7 on 2025-04-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcheck', '0005_alter_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='card_type',
            field=models.CharField(choices=[('code_quality', 'Code Quality'), ('requirements_clarity', 'Requirements Clarity'), ('testing_coverage', 'Testing Coverage'), ('deployment_process', 'Deployment Process'), ('tooling_infrastructure', 'Tooling & Infrastructure'), ('team_collaboration', 'Team Collaboration'), ('delivery_predictability', 'Delivery Predictability'), ('stakeholder_communication', 'Stakeholder Communication'), ('knowledge_sharing', 'Knowledge Sharing'), ('workload_balance', 'Workload Balance')], max_length=30),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.CharField(choices=[('good', 'Good'), ('neutral', 'Neutral'), ('needs_improvement', 'Needs Improvement')], max_length=30),
        ),
    ]
